INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-01-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-02-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-03-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-04-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-05-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-06-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-07-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-08-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-09-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-10-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-11-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2021-12-01', 'HOUSING');

INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-01-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-02-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-03-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-04-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-05-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-06-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-07-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-08-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-09-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-10-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-11-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2022-12-01', 'HOUSING');


INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-01-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-02-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-03-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-04-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-05-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-06-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-07-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-08-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-09-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-10-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-11-01', 'HOUSING');
INSERT INTO `money`.`trans` (`id`, `business`, `money`, `items`, `date`, `category`) VALUES (NULL, 'NAME-BUS', 0.00, 'NAME-DESC', '2023-12-01', 'HOUSING');